blueprint:
  name: Reusable Scene Snapshot
  description: This blueprint captures a snapshot of selected entities, sets them to a brightness, and restores them when run again.
  domain: script
  input:
    scene_id:
      name: Scene ID
      description: The ID for the scene to store or restore
      default: "zithoek_snapshot"
    brightness_pct:
      name: Brightness Percentage
      description: The brightness percentage for the lights
      number:
        min: 1
        max: 100
        step: 1
        mode: slider
      default: 100
    snapshot_entities:
      name: Entities to Snapshot
      description: A list of entities to be captured in the scene
      entity:
        domain: light
        multiple: true
      default: []

sequence:
  - variables:
      scene_id: !input scene_id
      brightness_pct: !input brightness_pct
      snapshot_entities: !input snapshot_entities
  - choose:
    - conditions:
        - condition: template
          value_template: "{{ states.scene[scene_id] == None }}"
      sequence:
        - service: scene.create
          data:
            scene_id: "{{ scene_id }}"
            snapshot_entities: "{{ snapshot_entities }}"
        - service: light.turn_on
          data:
            brightness_pct: "{{ brightness_pct }}"          
          target:
            entity_id: "{{ snapshot_entities }}"
    - conditions:
        - condition: template
          value_template: "{{ states.scene[scene_id] is not none }}"
      sequence:
        - service: scene.turn_on
          data:
            entity_id: "scene.{{ scene_id }}"
        - service: scene.delete
          data:
            entity_id: "scene.{{ scene_id }}"
    default: []
