blueprint:
  name: ButtonPlus Cleanup Buttons
  description: >
    Reset button configurations based on specific conditions. You can specify 
    either or both `toplabel` and `label` values to match.
  domain: automation
  input:
    entities:
      name: Input Text Entities
      description: List of input_text entities to clean up.
      selector:
        entity:
          domain: input_text
          multiple: true
    trigger_time:
      name: Cleanup Trigger Time
      description: Time to trigger the cleanup process.
      selector:
        time:
    toplabel_match:
      name: Toplabel Match (Optional)
      description: Value of the toplabel to match. Leave empty to ignore.
      selector:
        text:
      default: ""
    label_match:
      name: Label Match (Optional)
      description: Value of the label to match. Leave empty to ignore.
      selector:
        text:
      default: ""

trigger:
  - platform: time
    at: !input trigger_time

condition: []

action:
  - repeat:
      for_each: !input entities
      sequence:
        - variables:
            raw_value: |
              {% set raw = states(repeat.item) | default('') %}
              {% if raw == '' %}
                {}
              {% else %}
                {{ raw | from_json | default({}) }}
              {% endif %}
        - if:
            - condition: template
              value_template: >
                {% set toplabel_check = !input toplabel_match | string %}
                {% set label_check = !input label_match | string %}
                {{ 
                  (toplabel_check == "" or 
                   ('toplabel' in raw_value and raw_value['toplabel'] == toplabel_check)) and
                  (label_check == "" or 
                   ('label' in raw_value and raw_value['label'] == label_check))
                }}
          then:
            - service: input_text.set_value
              target:
                entity_id: "{{ repeat.item }}"
              data:
                value: "{}"
mode: queued