blueprint:
  name: "Extra Heating"
  domain: automation
  description: "Heating blueprint created by Martijn for flexible control."
  homeassistant:
    min_version: 2024.1.0
  input:
    climate_entity:
      name: "Climate entity"
      default: climate.zolder
      selector:
        entity:
          domain: climate
    switch_entity:
      name: "Switch entity"
      default: switch.bijzetkachel_1_schakelaar
      selector:
        entity:
          domain: switch
    temperature_threshold:
      name: "Required temperature difference"
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1
          mode: slider
      default: 1
    roc_sensor:
      name: "Rate-of-change sensor"
      selector:
        entity:
          domain: sensor
      default: sensor.zolder_temperature_rate_of_change
    roc_below:
      name: "ROC below threshold"
      selector:
        number:
          min: 0.01
          max: 1
          step: 0.01
          mode: slider
      default: 0.05
    roc_duration:
      name: "ROC duration (HH:MM:SS)"
      selector:
        duration:
      default:
        hours: 0
        minutes: 15
        seconds: 0
    wait_timeout:
      name: "Heating timeout (HH:MM:SS)"
      selector:
        duration:
      default:
        hours: 1
        minutes: 0
        seconds: 0

trigger:
  - platform: state
    entity_id: !input climate_entity
    attribute: hvac_action
    to: heating

variables:
  temperature: "{{ state_attr(!input climate_entity, 'temperature') | float }}"
  current_temperature: "{{ state_attr(!input climate_entity, 'current_temperature') | float }}"
  climate_entity: !input climate_entity
  temperature_threshold: !input temperature_threshold

condition:
  - condition: template
    value_template: "{{ (state_attr(climate_entity, 'temperature') | float) - (state_attr(climate_entity, 'current_temperature') | float) >= temperature_threshold }}"

action:
  - service: switch.turn_on
    target:
      entity_id: !input switch_entity
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: !input roc_sensor
      for: !input roc_duration
      below: !input roc_below
    - platform: state
      entity_id: !input climate_entity
      attribute: hvac_action
      from: heating
    timeout: !input wait_timeout
  - service: switch.turn_off
    target:
      entity_id: !input switch_entity

mode: single